#
# Copyright (c) 2018 Juniper Networks, Inc. All rights reserved.
#

Import('K8sClientEnv')

env = K8sClientEnv.Clone()

env.Append(CPPPATH = env['TOP'])
env.Append(CPPPATH = [env['TOP'] + '/database'])

env.Append(CXXFLAGS = '-Wno-deprecated-declarations -DGTEST_USE_OWN_TR1_TUPLE=1 -std=c++11')

def MapBuildDir(list):
    return map(lambda x: env['TOP'] + '/' + x, list)

env.Prepend(LIBS=[  'io',
                    'sandesh',
                    'http',
                    'http_parser',
                    'pugixml',
                    'xml',
                    'curl',
                    'sandeshvns',
                    'process_info',
                    'io',
                    'base',
                    'ssl',
                    'crypto',
                    'gunit',
                    'boost_regex',
                    'k8s_client',
                    'restclient-cpp'
                    ])

libs = MapBuildDir([
        'xml',
        'base',
        'io',
        'sandesh'])

env.Append(LIBPATH=libs)

env.Prepend(LINKFLAGS=['-Wl,--whole-archive', '-lbase','-Wl,--no-whole-archive' ])

k8s_client_test = env.UnitTest('k8s_client_test',
                              ['k8s_client_test.cc'])

test_suite = []
test = env.TestSuite('k8s_client_test_suite', test_suite)
def_env = DefaultEnvironment()
env.Alias('src/contrail-common/database/k8s/k8s_client:test', test)

flaky_test_suite = [ k8s_client_test ]
flaky_test = env.TestSuite('k8s_client_flaky_test_suite', flaky_test_suite)
env.Alias('src/contrail-common/database/k8s/k8s_client:flaky-test', flaky_test)
